#!/bin/bash


# declare -A search_space
# search_space['n_layers']="1 2 3"
# search_space['n_head']="1 2 4 8"
# search_space['dim_model']="64 128 256"
# search_space['dim_hidden']="64 128 256"
# search_space['dim_k']="16 32 64 128"
# search_space['dim_v']="16 32 64 128"
# search_space['max_grad']="0.5 1 2"
# search_space['learning_rate']="1e-2 1e-3 1e-4 1e-5"
# search_space['learning_rate_gamma']="1 0.98 0.96"

# iteration=20
# for i in $( eval echo {1..$iteration} ); do
# 	config_file="config_file${i}"
# 	echo "[config]
# model=TSP_improve
# environment = Improvement
# data_path = runs/config${i}
# save_csv = True
# save_tensor = True
# n_batch = 10
# n_batch_train_size = 512
# n_batch_test_size = 1024
# T = 1
# baseline_type = ExpMovingAvg" > $config_file
# 	for key in "${!search_space[@]}"; do
# 		# select random element
# 		list=${search_space[$key]}
# 		list=($list)
# 		echo "${list}"
# 		size=${#list[@]}
# 		index=$(($RANDOM % $size))
# 		element=${list[$index]}
# 		# add to file
# 		echo "$key = $element" >> $config_file
# 	done
# 	# run code
# 	# python3 Main.py -f config_file
# done

N_NODES=5
EPOCH=10
arrayName=(11 14)
for i in "${arrayName[@]}"; do
	filename="./runs/configFiles/PointerNetwork-${i}"
	tsp python3 Main.py $filename $EPOCH $N_NODES
done

# N_NODES=5
# EPOCH=2
# for filename in ./runs/configFiles/Transformer-*; do
# 	tsp python3 Main.py $filename $EPOCH $N_NODES
# done
