#!/bin/bash


declare -A search_space
search_space['processing']="1 2 3"
search_space['embedding']="64 128 256"
search_space['hidden']="64 128 256"
search_space['glimpse']="0 1 2"
search_space['max_grad']="0.5 1 2"
search_space['learning_rate']="1e-2 1e-3 1e-4 1e-5"
search_space['learning_rate_gamma']="1 0.98 0.96"

iteration=1
for i in $( eval echo {1..$iteration} ); do
	config_file="config_file${i}"
	echo "[general]
model=PointerNetwork
environment = Construction
data_path = runs/config${i}
save_csv = True
save_tensor = False
n_batch = 10
n_batch_train_size = 512
n_batch_test_size = 1024
baseline_type = ExpMovingAvg" > $config_file
	for key in "${!search_space[@]}"; do
		# select random element
		list=${search_space[$key]}
		list=($list)
		echo "${list}"
		size=${#list[@]}
		index=$(($RANDOM % $size))
		element=${list[$index]}
		# add to file
		echo "$key = $element" >> $config_file
	done
	# run code
	tsp python python_script.py -f config_file
done