#!/bin/bash
N_NODES=5
EPOCH=10
arrayName=(0 14)
# for filename in ./runs/configFiles/PointerNetwork-*; do
for i in "${arrayName[@]}"; do
	filename="./runs/configFiles/PointerNetwork-${i}"
	tsp python3 Main.py $filename $EPOCH $N_NODES
done

# N_NODES=5
# EPOCH=2
# for filename in ./runs/configFiles/Transformer-*; do
# 	tsp python3 Main.py $filename $EPOCH $N_NODES
# done
