#!/bin/bash
N_NODES=5
EPOCH=10
arrayName=(3 7)
# for filename in ./runs/configFiles/Transformer-*; do
for i in "${arrayName[@]}"; do
	filename="./runs/configFiles/Transformer-${i}"
	tsp python3 Main.py $filename $EPOCH $N_NODES
done
